server:
  port: ${PORT:8090}
kafka:
  server: 'localhost:9092'
  group: 'group_one'
  offset: 'earliest'
  topics:
    receivemessage: 'org.telegram.bot.receivemessage'
    sendmessage: 'org.telegram.bot.sendmessage'
logging:
  level:
    root: off
    org:
      telegram:
        bot:
          facadebot: debug