server:
  port: ${PORT:8090}
kafka:
  server: 'localhost:9092'
  group: 'group_one'
  offset: 'earliest'
  topics:
    receivemessage: 'org.telegram.bot.receivemessage'
    sendmessage: 'org.telegram.bot.sendmessage'
logging:
  level:
    root: off
    org:
      telegram:
        bot:
          facadebot: debug
cloudkarafka:
  topic:
    receivemessage: '${CLOUDKARAFKA_USERNAME}-org.telegram.bot.receivemessage'
    receiveadminmessage: '${CLOUDKARAFKA_USERNAME}-org.telegram.bot.receiveadminmessage'
    sendmessage: '${CLOUDKARAFKA_USERNAME}-org.telegram.bot.sendmessage'
    sendadminmessage: '${CLOUDKARAFKA_USERNAME}-org.telegram.bot.sendadminmessage'
spring:
  kafka:
    bootstrap-servers: ${CLOUDKARAFKA_BROKERS}
    consumer:
      auto-offset-reset: latest
      group-id: ${CLOUDKARAFKA_USERNAME}-consumers
      properties:
        spring:
          json:
            trusted:
              packages: sample.kafka
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule
            required username="${CLOUDKARAFKA_USERNAME}" password="${CLOUDKARAFKA_PASSWORD}";
        mechanism: SCRAM-SHA-256
      security:
        protocol: SASL_SSL
