server:
  port: ${PORT:8090}
logging:
  level:
    root: off
    org:
      telegram:
        bot:
          facadebot: debug
kafka:
  consumer: ${KAFKA_CONSUMER}
  server: ${KAFKA_SERVER}
  jaas: ${KAFKA_JAAS_CONFIG}
  topic:
    sendmessage: '${KAFKA_USERNAME}-org.telegram.bot.sendmessage'
    receivemessage: '${KAFKA_USERNAME}-org.telegram.bot.receivemessage'
    sizesrequest: '${KAFKA_USERNAME}-org.telegram.bot.availablesizesrequest'
    sizesresponse: '${KAFKA_USERNAME}-org.telegram.bot.availablesizesresponse'
    newalert: '${KAFKA_USERNAME}-org.telegram.bot.newalert'
bot:
  name: ${TELEGRAM_NAME}
  token: ${TELEGRAM_TOKEN}
  admin: ${ADMIN_CHATID}
